---
- name: Install Nginx
  ansible.builtin.apt:
    pkg:
      - certbot
      - nginx
      - python3-certbot-nginx
    state: present
  tags:
    - nginx

- name: Configure nginx MIME types
  ansible.builtin.template:
    src: mime.types.j2
    dest: /etc/nginx/mime.types
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx
  tags:
    - nginx

- name: Configure nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart nginx
  tags:
    - nginx

- name: Configure nginx default server
  ansible.builtin.template:
    src: default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload nginx
  tags:
    - nginx

- name: Enable nginx default server
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - Reload nginx
  tags:
    - nginx
