---
- name: Reconfigure locales
  ansible.builtin.command: dpkg-reconfigure -f noninteractive locales
  changed_when: true

- name: Reconfigure tzdata
  ansible.builtin.command: dpkg-reconfigure -f noninteractive tzdata
  changed_when: true

- name: Restart timesyncd
  ansible.builtin.service:
    name: systemd-timesyncd
    state: restarted

- name: Restart cron
  ansible.builtin.service:
    name: cron
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart nftables
  ansible.builtin.service:
    name: nftables
    state: restarted

- name: Make dotfiles
  ansible.builtin.shell:
    cmd: make
    chdir: /home/{{ item.item.name }}/.dotfiles
  become: true
  become_user: "{{ item.item.name }}"
  changed_when: true
  when: item is changed
  loop: "{{ dotfiles.results }}"
